name: Project-0

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      working-directory: project-0
      run: |
        echo "Processing in this directory: ${{ github.event.inputs.project_directory }}"
        docker build . --file Dockerfile --tag python:sample
    - name: Run Docker container
        echo "Running Docker Container"
        docker run --rm python:sample > ${{ github.event.inputs.project_directory }}/output.txt
        # Add the output.txt file to git
        git add ${{ github.event.inputs.project_directory }}/output.txt
    - name: Commit output.txt
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git commit -m "Save output.txt for ${{ github.event.inputs.project_directory }}"
        git push
