name: Project-2

on:
  push:
    branches: [ "main" ]
    paths:
      - 'project-2/**'  # Trigger workflow if changes occur in this directory

jobs:
  build:
    runs-on: ubuntu-latest

steps:
  - uses: actions/checkout@v4
  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: '3.12'
  - name: Install Dependencies
    run: |
      python -m pip install --upgrade pip setuptools wheel
      python -m pip install scikit-learn pandas matplotlib
  - name: Run the Iris plot script
    run: |
      python plot-iris.py
  # Step 5: Upload the generated output image (output.png)
  - name: Upload the output image
    uses: actions/upload-artifact@v3
    with:
      name: iris-plot
      path: output.png
