name: Project-2

on:
  push:
    branches: [ "main" ]
    paths:
      - 'project-2/**'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install pandas scikit-learn matplotlib

      - name: Run the Iris plot script
        working-directory: project-2
        run: |
          python plot-iris.py
      
      - name: Commit and push the output file
        working-directory: project-2
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          timestamp=$(date +"%Y%m%d-%H%M%S")
          mv sepal-length-vs-width.png sepal-length-vs-width-$timestamp.png
          git add sepal-length-vs-width-$timestamp.png
          git commit -m "Save plot with $timestamp"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
