name: Project-0

on:
  push:
    branches: [ "main" ]
    paths:
      - 'project-0/**'  # Trigger workflow if changes occur in this directory

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      working-directory: project-0
      run: |
        echo "Processing in directory: project-0"
        docker build . --file Dockerfile --tag python:sample

    - name: Run Docker container
      working-directory: project-0
      run: |
        echo "Running Docker Container"
        docker run --rm python:sample > output.txt
        git add output.txt

    - name: Check for changes
      run: |
        git fetch origin main
        if git diff --quiet origin/main; then
          echo "No changes to push";
          exit 0;
        fi

    - name: Commit output.txt
      working-directory: project-0
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git commit -m "Save output.txt for project-0"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}