name: Project-2

on:
  push:
    branches: [ "main" ]
    paths:
      - 'project-2/**'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install pandas scikit-learn matplotlib

      - name: Run the Iris plot script
        run: |
          python project-2/plot-iris.py
          ls -lh /home/runner/work

      - name: Upload the output image
        uses: actions/upload-artifact@v3
        with:
          name: iris-plot
          path: project-2/output.png
