name: Project-2

on:
  push:
    branches: [ "main" ]
    paths:
      - 'project-2/**'  # Trigger workflow if changes occur in this directory

jobs:
  build:
    runs-on: ubuntu-latest

steps:
  - uses: actions/checkout@v4
  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: '3.12'
  - name: Install Dependencies
    run: |
      python -m pip install --upgrade pip setuptools wheel
      python -m pip install scikit-learn seaborn
  - name: Lint with Ruff
    working-directory: project-2
    run: |
      python -m pip install ruff
      ruff check --output-format=github .
  